export let products = [
  // Categoría: Camas
  {
    id: 1,
    title: "Cama Queen",
    description: "Cama tamaño queen con cabecera tapizada",
    price: 300.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625144/cama_queen_apdg6n.jpg",
    stock: 13,
    category: "Camas",
  },
  {
    id: 2,
    title: "Cama Individual",
    description: "Cama individual con estructura de metal",
    price: 150.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625140/cama_individual_narkmy.jpg",
    stock: 13,
    category: "Camas",
  },
  {
    id: 3,
    title: "Cama King",
    description: "Cama tamaño king con base de madera",
    price: 400.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625140/cama_king_v5xm7v.jpg",
    stock: 13,
    category: "Camas",
  },

  // Categoría: Escritorios
  {
    id: 4,
    title: "Escritorio de oficina",
    description: "Escritorio de oficina con cajones",
    price: 180.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625140/escritorio_oficina_dplqps.jpg",
    stock: 13,
    category: "Escritorios",
  },
  {
    id: 5,
    title: "Escritorio de estudio",
    description: "Escritorio compacto para estudio",
    price: 120.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625143/escritorio_estudio_hdwyas.jpg",
    stock: 13,
    category: "Escritorios",
  },
  {
    id: 6,
    title: "Escritorio con estantería",
    description: "Escritorio con estantería integrada",
    price: 200.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625140/escritorio_estanteria_z6jffm.jpg",
    stock: 13,
    category: "Escritorios",
  },

  // Categoría: Mesas
  {
    id: 7,
    title: "Mesa de comedor",
    description: "Mesa de comedor de madera para seis personas",
    price: 150.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625139/mesa_comedor_n8t8c1.jpg",
    stock: 13,
    category: "Mesas",
  },
  {
    id: 8,
    title: "Mesa de centro",
    description: "Mesa de centro de vidrio templado",
    price: 120.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625139/mesa_centro_akhqrt.jpg",
    stock: 13,
    category: "Mesas",
  },
  {
    id: 9,
    title: "Mesa auxiliar",
    description: "Mesa auxiliar redonda de metal",
    price: 80.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625143/mesa_auxiliar_fn7zq1.jpg",
    stock: 13,
    category: "Mesas",
  },

  // Categoría: Roperos
  {
    id: 10,
    title: "Armario de dos puertas",
    description: "Armario de dos puertas con espejo",
    price: 220.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625139/armario_dos_puertas_nb32az.jpg",
    stock: 13,
    category: "Roperos",
  },
  {
    id: 11,
    title: "Ropero de madera",
    description: "Ropero de madera con múltiples compartimentos",
    price: 300.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625139/ropero_madera_cwscyr.jpg",
    stock: 13,
    category: "Roperos",
  },
  {
    id: 12,
    title: "Armario empotrado",
    description: "Armario empotrado con puertas corredizas",
    price: 400.0,
    img: "https://res.cloudinary.com/dxxpxlqdl/image/upload/v1719625139/armario_empotrado_rczkte.jpg",
    stock: 13,
    category: "Roperos",
  },
];
