export let products = [
  // Categoría: Camas
  {
    id: 1,
    title: "Cama Queen",
    description: "Cama tamaño queen con cabecera tapizada",
    price: 300.0,
    img: "https://example.com/images/cama_queen.jpg",
    stock: 13,
    category: "Camas",
  },
  {
    id: 2,
    title: "Cama Individual",
    description: "Cama individual con estructura de metal",
    price: 150.0,
    img: "https://example.com/images/cama_individual.jpg",
    stock: 13,
    category: "Camas",
  },
  {
    id: 3,
    title: "Cama King",
    description: "Cama tamaño king con base de madera",
    price: 400.0,
    img: "https://example.com/images/cama_king.jpg",
    stock: 13,
    category: "Camas",
  },

  // Categoría: Escritorios
  {
    id: 4,
    title: "Escritorio de oficina",
    description: "Escritorio de oficina con cajones",
    price: 180.0,
    img: "https://example.com/images/escritorio_oficina.jpg",
    stock: 13,
    category: "Escritorios",
  },
  {
    id: 5,
    title: "Escritorio de estudio",
    description: "Escritorio compacto para estudio",
    price: 120.0,
    img: "https://example.com/images/escritorio_estudio.jpg",
    stock: 13,
    category: "Escritorios",
  },
  {
    id: 6,
    title: "Escritorio con estantería",
    description: "Escritorio con estantería integrada",
    price: 200.0,
    img: "https://example.com/images/escritorio_estanteria.jpg",
    stock: 13,
    category: "Escritorios",
  },

  // Categoría: Mesas
  {
    id: 7,
    title: "Mesa de comedor",
    description: "Mesa de comedor de madera para seis personas",
    price: 150.0,
    img: "https://example.com/images/mesa_comedor.jpg",
    stock: 13,
    category: "Mesas",
  },
  {
    id: 8,
    title: "Mesa de centro",
    description: "Mesa de centro de vidrio templado",
    price: 120.0,
    img: "https://example.com/images/mesa_centro.jpg",
    stock: 13,
    category: "Mesas",
  },
  {
    id: 9,
    title: "Mesa auxiliar",
    description: "Mesa auxiliar redonda de metal",
    price: 80.0,
    img: "https://example.com/images/mesa_auxiliar.jpg",
    stock: 13,
    category: "Mesas",
  },

  // Categoría: Roperos
  {
    id: 10,
    title: "Armario de dos puertas",
    description: "Armario de dos puertas con espejo",
    price: 220.0,
    img: "https://example.com/images/armario_dos_puertas.jpg",
    stock: 13,
    category: "Roperos",
  },
  {
    id: 11,
    title: "Ropero de madera",
    description: "Ropero de madera con múltiples compartimentos",
    price: 300.0,
    img: "https://example.com/images/ropero_madera.jpg",
    stock: 13,
    category: "Roperos",
  },
  {
    id: 12,
    title: "Armario empotrado",
    description: "Armario empotrado con puertas corredizas",
    price: 400.0,
    img: "https://example.com/images/armario_empotrado.jpg",
    stock: 13,
    category: "Roperos",
  },
];
